export function generateReferenceNumber(_reportType: string, _dateReported: string, _existingReferenceNumbers: string[]) {
  throw new Error('Reference numbers are now generated by PostgreSQL via public.generate_reference_number.');
}
