export const reportBuildingOptions = [
  "GLE Building",
  "Acad Building",
  "Allied Building",
  "NGE Building",
  "RTL Building",
  "SAL Building",
  "G-LEC Area",
  "G-SMART Area",
  "Espacio",
  "College Canteen",
  "Main Canteen",
  "Elementary Canteen",
  "College Library",
  "SHS Library",
  "JHS Library",
  "Study Area",
  "Gym",
  "Accounting Area",
  "RTL Lobby",
  "PE Area",
  "Back Gate",
  "Front Gate",
];
